AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

require:
  - rubocop-capybara
  - rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
