version: "3.9"
services:
  test_runner:
    container_name: hostelworld-sherpa-test-runner
    hostname: test_runner
    ports:
      - 127.0.0.1:8080:8080
    build:
      context: .
      dockerfile: dockerfiles/test_runner.dockerfile
    working_dir: /test_runner
    volumes:
      - .:/test_runner
    command: tail -f /dev/null
    networks:
      - test-network

  selenium:
    container_name: hostelworld-sherpa-selenium
    image: selenium/standalone-chromium:131.0
    hostname: selenium
    ports:
      - 127.0.0.1:4444:4444
      - 127.0.0.1:5900:5900
      - 127.0.0.1:7900:7900
    environment:
      - SE_VNC_NO_PASSWORD=1
    volumes:
      - ./extension:/extension
    networks:
      - test-network

networks:
  test-network:
