version: "3.9"
services:
  selenium:
    image: selenium/standalone-chromium:131.0
    hostname: selenium
    container_name: hostelworld-sherpa-selenium
    ports:
      - 127.0.0.1:4444:4444
      - 127.0.0.1:5900:5900
      - 127.0.0.1:7900:7900
    environment:
      - SE_VNC_NO_PASSWORD=1
